In [1]:
!pip istall numpy


ERROR: unknown command "istall" - maybe you meant "install"



In [3]:
!pip install numpy

In [5]:
import numpy as np
array_zeros = np.zeros(10)
print(array_zeros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [9]:
array_ones=np.ones(10)
print(array_ones)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [13]:
array_five=np.full(10,5)
print(array_five)


[5 5 5 5 5 5 5 5 5 5]


In [17]:
array_of_integers=np.arange(10,51)
print(array_of_integers)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


In [19]:
array_of_even=np.arange(10,51,2)
print(array_of_even)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


In [23]:
matrix_3=np.arange(9).reshape(3,3)
print(matrix_3)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [28]:
random_number=np.random.rand()
print(random_number)

0.14669402960867528


In [30]:
random_numbers=np.random.randn(25)
print(random_numbers)

[ 0.28529375 -1.12377844  0.19152668 -0.78629169 -0.0312828   2.07488827
  1.06262028 -1.12004762  0.59238343  0.41570914 -0.67000014  1.64469066
 -1.5395141   0.16302067 -0.00626619  0.25619737 -0.93533658  0.34327845
  1.44678927  1.20910808  0.87603069 -0.19424342  0.15092439 -1.49042084
  2.02502951]


In [32]:
array_10=np.arange(0.01,1.01,0.01).reshape(10,10)
print(array_10)

[[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 ]
 [0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.2 ]
 [0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.3 ]
 [0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4 ]
 [0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5 ]
 [0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.6 ]
 [0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7 ]
 [0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8 ]
 [0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89 0.9 ]
 [0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.99 1.  ]]


In [34]:
linear_space=np.linspace(0,1,20)
print(linear_space)

[0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]


In [36]:
array_5=np.arange(1,26).reshape(5,5)
print(array_5)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [42]:
array_5=np.arange(1,26).reshape(5,5)
subarray=array_5[2:5,1:5]
print(subarray)

[[12 13 14 15]
 [17 18 19 20]
 [22 23 24 25]]


In [44]:
number_20=subarray[1,3]
print(number_20)

20


In [54]:
colum1=array_5[0:3,1]
print(colum1)

[ 2  7 12]


In [56]:
last_row=array_5[-1]
print(last_row)

[21 22 23 24 25]


In [66]:
last_2row=array_5[3:5]
print(last_2row)

[[16 17 18 19 20]
 [21 22 23 24 25]]


In [70]:
summation=sum(sum(array_5))
print(summation)

325


In [72]:
standard=np.std(array_5)
print(standard)

7.211102550927978


In [76]:
summation_columns=sum(array_5)
print(summation_columns)

[55 60 65 70 75]
